### ISSUE TITLE
add work_time reference also for claims

### ISSUE THREAD

**Issue by giovanni-angeli** [giovanni-angeli/flask_tracker#1]
add the possibility of referencing **work_time** records to **claim** records (as for **task**).
 ~~Requested by: CC~~
Requested by: Marco R

**Comment by FrancescoGalasso** [comment]
released on [0.9.0rc1](https://github.com/giovanni-angeli/flask_tracker/commit/0642cd5dd5435d8f2a4866269a006b49c9c9bb66)
