### ISSUE TITLE
feed back IMPROVEMENT 1

### ISSUE THREAD

**Issue by giovanni-angeli** [giovanni-angeli/flask_tracker#11]
Silvia Calo ci segnala, rispetto al model IMPROVEMENT (#4 ) :

  * Il campo content non è subito visibile, bisogna salvare la richiesta e rientrare per far apparire il box.
  * E' possibile mettere un solo notifier ma, come per i claim, spesso è necessario coinvolgere più figure. Nei claim vengono chiamati followers.
  * Nel campo Machine Model manca la CR.

**Comment by giovanni-angeli** [comment]
@CaloSilvia riporto qui le richieste che raccolgo.

**Comment by FrancescoGalasso** [comment]
@CaloSilvia 

>Il campo content non è subito visibile, bisogna salvare la richiesta e rientrare per far apparire il box.

durante la fase di CREATE dell'IMPROVEMENT, giusto?

>E' possibile mettere un solo notifier ma, come per i claim, spesso è necessario coinvolgere più figure. Nei claim vengono >chiamati followers.

**TBI** (To Be Implemented)

>Nel campo Machine Model manca la CR.

Disponibile dal 22 Nov a seguito dell'aggiunta del Machine Model mancante all'interno di Flask Tracker conf file

**Comment by FrancescoGalasso** [comment]
released on [0.9.0rc1](https://github.com/giovanni-angeli/flask_tracker/commit/0642cd5dd5435d8f2a4866269a006b49c9c9bb66)
