### ISSUE TITLE
feed back IMPROVEMENT 2

### ISSUE THREAD

**Issue by giovanni-angeli** [giovanni-angeli/flask_tracker#12]
Giuliano ci segnala in merito a aggiunta nuovo model: IMPROVEMENT #4 :

Ciao Giovanni,
   L’estetica della prima pagina non è il massimo a causa della totale visualizzazione del content.
Inoltre mi rendo conto di avere parecchi suggerimenti per la PRODUZIONE, ora che qualcuno mi ascolta 😃 …quindi mi piacerebbe molto avere anche la scelta del department destinatario …“TO ______”

Grazie
![unnamed](https://user-images.githubusercontent.com/10273234/139858823-8b378962-7cbf-47a5-81ff-2816f950b190.jpg)

**Comment by FrancescoGalasso** [comment]
@giovanni-angeli 
confrontandomi con Giuliano ho compreso la sua necessità di creazione di una colonna aggiuntiva "target department" (dipartimento destinatario)

è altamente probabile che nel tempo il pattern "FROM dept A TO dept B" nel campo "Department" non verrà rispettato.
però l'introduzione di un nuovo attributo dovrebbe comportare una migrazione.
è corretto quanto dico?

**Comment by FrancescoGalasso** [comment]
released on [0.9.0rc1](https://github.com/giovanni-angeli/flask_tracker/commit/0642cd5dd5435d8f2a4866269a006b49c9c9bb66)
