### ISSUE TITLE
campo Damaged Group come colonna

### ISSUE THREAD

**Issue by giovanni-angeli** [giovanni-angeli/flask_tracker#3]
Ciao Giovanni,
sarebbe possibile visualizzare il campo Damaged Group come colonna (magari a discapito della colonna Date Modified)?
Cosicché Damaged Group diventi un filtro?
Così diventerebbe più semplice raccogliere info di rotture/malfunzionamenti legati appunto ad ogni specifico gruppo.
Facci sapere,
Grazie
Chasmine

**Comment by FrancescoGalasso** [comment]
@ChasmineCaiani @lgalfa @CaloSilvia 
se ho interpretato correttamente la richiesta questo dovrebbe essere il risultato finale.
Potete confermare?

nella list dei claim appare la colonna "**Damaged Group**"; inoltre è presente anche il relativo filtro.
![Screenshot (614)](https://user-images.githubusercontent.com/32903566/144591379-534a4fa7-0cc1-40ff-8792-5bdd1d3c7ba4.png)

Risultato della ricerca usando come filtro  "**Damaged Group**" la stringa "base" 
![Screenshot (615)](https://user-images.githubusercontent.com/32903566/144591389-46da4038-d7f1-4398-8a50-8a9dfc99c5b5.png)

**Comment by FrancescoGalasso** [comment]
released on [0.9.0rc1](https://github.com/giovanni-angeli/flask_tracker/commit/0642cd5dd5435d8f2a4866269a006b49c9c9bb66)
